### ISSUE TITLE
iDynTree Visualizer-based drop in replacement for iCubGui? 

### ISSUE THREAD

**Issue by traversaro** [robotology/idyntree-yarp-tools#1]
Given the latest development in the visualizer contained in iDynTree 3, it should be now relatively easy to develop a simple drop-in replacement for the [iCubGui](https://robotology.github.io/robotology-documentation/doc/html/group__icub__gui.html) that gets the configuration of the robot and the external force from YARP ports, but gets the kinematic model and the meshes of the robot from the URDF models rather then the custom BVH models used in iCubGui (see https://github.com/robotology/icub-main/pull/531/files). This may be convenient for new and custom robots developed now (such as iRonCub) or in the future.

**Comment by traversaro** [comment]
Done!

**Comment by traversaro** [comment]
Related PRs: 
* https://github.com/robotology/idyntree-yarp-tools/pull/4
* https://github.com/robotology/idyntree-yarp-tools/pull/5

@S-Dafarra my last doubt is on the name, could it make sense to call it `idyntree-yarp-visualizer` rather then `idyntree-visualizer`? I think this would help to avoid confusion w.r.t. other existing tools such as `idyntree-model-view` .

**Comment by S-Dafarra** [comment]
> Related PRs:
> 
> * #4
> * #5
> 
> @S-Dafarra my last doubt is on the name, could it make sense to call it `idyntree-yarp-visualizer` rather then `idyntree-visualizer`? I think this would help to avoid confusion w.r.t. other existing tools such as `idyntree-model-view` .

No problem for me! 

Regarding the visualization of the hands, I tried to connect to the robot while using the ``iCubGazeboV2_5_visuomanip`` model, but I had an error because some of the hands' joint names do not coincide with the robot ones.

**Comment by traversaro** [comment]
> Regarding the visualization of the hands, I tried to connect to the robot while using the iCubGazeboV2_5_visuomanip model, but I had an error because some of the hands' joint names do not coincide with the robot ones.

Good to know. This is a byproduct of https://github.com/robotology/icub-models/issues/30 .

**Comment by lrapetti** [comment]
> What is still missing:
> 
> visualization of external wrenches

Just to document it somewhere, I recently ended up in the following "issue":
I needed to visualize the wrench associated to a frame of the model, but currently there is no direct way to get the frame pose from a visualized model, but only links frame are exposed with [`getWorldLinkTransform `](https://github.com/robotology/idyntree/blob/master/src/visualization/src/ModelVisualization.h#L53). Do you think it makes sense to open an issue in `iDynTree` in order to add a `getFrameTransform` method, or do you have other strategies to achieve that?

**Comment by S-Dafarra** [comment]
> > What is still missing:
> > visualization of external wrenches
> 
> Just to document it somewhere, I recently ended up in the following "issue":
> I needed to visualize the wrench associated to a frame of the model, but currently there is no direct way to get the frame pose from a visualized model, but only links frame are exposed with [`getWorldLinkTransform `](https://github.com/robotology/idyntree/blob/master/src/visualization/src/ModelVisualization.h#L53). Do you think it makes sense to open an issue in `iDynTree` in order to add a `getFrameTransform` method, or do you have other strategies to achieve that?

Yes, I think we can add it easily. The trick would be to retrieve from the model the frame parent link (https://robotology.github.io/idyntree/master/classiDynTree_1_1Model.html#a64e8453f19a7c6f4e9dd0d9063062854), and the corresponding relative transformation (https://robotology.github.io/idyntree/master/classiDynTree_1_1Model.html#ad3e8276d1ec7e275aadeb75c1add80b6). Then, it is just matter of chaining the two transformations together. 
We can hide this complexity in the interface though.

**Comment by lrapetti** [comment]
> Then, it is just matter of chaining the two transformations together.
> We can hide this complexity in the interface though.

PR opened at https://github.com/robotology/idyntree/pull/849

**Comment by lrapetti** [comment]
I think this issue can be closed since the `idyntree-yarp-visualizer` is now being used

**Comment by traversaro** [comment]
Yes, it is not strictly speaking a drop-in replacement for iCubGui, but I guess at this point that is ok.
