### ISSUE TITLE
Handle deprecation of ``transformClient`` (to be removed in the next release of YARP)

### ISSUE THREAD

**Issue by lrapetti** [robotology/idyntree-yarp-tools#48]
Related issues:
- https://github.com/robotology/walking-teleoperation/issues/131
- https://github.com/robotology/wearables/issues/191

It is used in some of the tools contained in this repo.

cc @S-Dafarra @traversaro

**Comment by S-Dafarra** [comment]
Ah dammit, I forgot about it

**Comment by lrapetti** [comment]
cc @dariosortino

**Comment by lrapetti** [comment]
Thanks @S-Dafarra, can we do a Release following this fix?

**Comment by S-Dafarra** [comment]
> Thanks @S-Dafarra, can we do a Release following this fix?

Sure, done in https://github.com/robotology/idyntree-yarp-tools/releases/tag/v0.0.9
